### ISSUE TITLE
必须要开通微信支付吗？是否可以关闭？

### ISSUE THREAD

**Issue by godJBJ** [pea-cake/tbk#4]
下面是报错信息：

16:46:07 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:你需要开通微信支付，才可继续操作。
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GError: type() {
        return this._type;
    }(你需要开通微信支付，才可继续操作。)
    at Function.from (D:\project\tbkJs\node_modules\gerror\dist\cjs\src\gerror\gerror.js:86:23)
    at Bridge.onDialog (D:\project\tbkJs\node_modules\wechaty-puppet-wechat\dist\cjs\src\bridge.js:134:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (D:\project\tbkJs\node_modules\wechaty\dist\cjs\src\wechaty-mixins\gerror-mixin.js:48:26)
    at PuppetWeChat.<anonymous> (D:\project\tbkJs\node_modules\wechaty\dist\cjs\src\wechaty-mixins\puppet-mixin.js:181:34) 
    at PuppetWeChat.emit (node:events:513:28)
    at PuppetWeChat.emit (D:\project\tbkJs\node_modules\wechaty-puppet\dist\cjs\src\puppet\puppet-skeleton.js:133:22)      
    at Bridge.<anonymous> (D:\project\tbkJs\node_modules\wechaty-puppet-wechat\dist\cjs\src\puppet-wechat.js:197:45)       
    at Bridge.emit (node:events:513:28)
    at D:\project\tbkJs\node_modules\wechaty-puppet-wechat\dist\cjs\src\bridge.js:43:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(你需要开通微信支付，才可继续操作。)\n' +
    '    at Function.from (D:\\project\\tbkJs\\node_modules\\gerror\\dist\\cjs\\src\\gerror\\gerror.js:86:23)\n' +
    '    at Bridge.onDialog (D:\\project\\tbkJs\\node_modules\\wechaty-puppet-wechat\\dist\\cjs\\src\\bridge.js:134:44)\n' 
+
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by pea-cake** [comment]
这是微信的限制，没办法
